version: 2
updates:

  # epublib-parent
  - package-ecosystem: "maven"
    directory: "epublib-parent"
    schedule:
      interval: "monthly"

  # epublib-core
  - package-ecosystem: "maven"
    directory: "epublib-core"
    schedule:
      interval: "monthly"

  # epublib-tools
  - package-ecosystem: "tools"
    directory: "epublib-parent"
    schedule:
      interval: "monthly"